import { useEffect, useMemo, useRef, useState } from "react";
import { createApi, type CreditBalance } from "./api";
import { BrandMark } from "./BrandMark";

export function BillingPage({ accessToken, onBack, purchaseIntent }: { accessToken?: string; onBack: () => void; purchaseIntent?: "credits" | "subscription" }) {
  const api = useMemo(() => createApi(accessToken), [accessToken]); const [balance, setBalance] = useState<CreditBalance>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false); const [creditPackQuantity, setCreditPackQuantity] = useState(1);
  const creditPrice = import.meta.env.VITE_CREDIT_PACK_PRICE_ID; const subscriptionPrice = import.meta.env.VITE_SUBSCRIPTION_PRICE_ID;
  useEffect(() => { void api.balance().then(setBalance).catch(() => setError("We could not load your credit balance.")); }, [api]);
  async function checkout(kind: "credits" | "subscription", priceId: string, quantity = 1) { setBusy(true); setError(undefined); try { window.location.assign((await api.checkout(kind, priceId, quantity)).url); } catch { setError("We could not start checkout. Please try again."); setBusy(false); } }
  async function manage() { setBusy(true); try { window.location.assign((await api.portal()).url); } catch { setError("We could not open billing management."); setBusy(false); } }
  const handledPurchaseIntent = useRef(false);
  useEffect(() => { if (!purchaseIntent || handledPurchaseIntent.current) return; const priceId = purchaseIntent === "credits" ? creditPrice : subscriptionPrice; if (!priceId) { setError("Checkout is not configured yet. Please try again shortly."); return; } handledPurchaseIntent.current = true; void checkout(purchaseIntent, priceId); }, [creditPrice, purchaseIntent, subscriptionPrice]);
  const credits = balance ? balance.subscription_remaining + balance.purchased_credits : 0;
  const creditsPerPack = Number(import.meta.env.VITE_CREDIT_PACK_CREDITS ?? "20");
  const totalCredits = creditsPerPack * creditPackQuantity;
  const totalPrice = (5 * creditPackQuantity).toFixed(2);
  return <div className="workspace-shell"><header className="workspace-header"><button className="brand-button" onClick={onBack} type="button"><BrandMark /></button><button className="icon-button" onClick={onBack} type="button">Back to workspace</button></header><main className="billing-page"><p className="eyebrow">ACCOUNT & BILLING</p><h1>Keep your applications moving.</h1><p>Use your own Anthropic key anytime, or use Rezzie credits when you want the managed service.</p><section className="credit-summary"><strong>{credits}</strong><span>available Rezzie credits</span><small>{balance?.subscription_status === "active" ? "Your monthly plan is active." : "No active monthly plan."}</small></section>{error && <p className="auth-error" role="alert">{error}</p>}<div className="billing-plans"><article><p className="eyebrow">FLEX CREDITS</p><h2>$5 for {creditsPerPack} credits</h2><p>Choose how many packs to purchase. Purchased credits do not expire.</p>{creditPrice ? <><label className="quantity-control" htmlFor="credit-pack-quantity">Packs to buy<select id="credit-pack-quantity" value={creditPackQuantity} onChange={event => setCreditPackQuantity(Number(event.target.value))}>{Array.from({ length: 10 }, (_, index) => index + 1).map(quantity => <option key={quantity} value={quantity}>{quantity} pack{quantity === 1 ? "" : "s"} · {creditsPerPack * quantity} credits · ${(5 * quantity).toFixed(2)}</option>)}</select></label><button className="button button-primary" disabled={busy} onClick={() => void checkout("credits", creditPrice, creditPackQuantity)} type="button">Buy {totalCredits} credits for ${totalPrice}</button></> : <small>Credit packs will appear here when checkout is configured.</small>}</article><article className="featured"><p className="eyebrow">MONTHLY</p><h2>$9.99 / month</h2><p>Receive 50 credits each month while you are actively applying.</p>{subscriptionPrice ? <button className="button button-primary" disabled={busy} onClick={() => void checkout("subscription", subscriptionPrice)} type="button">Upgrade to monthly</button> : <small>Monthly plans will appear here when checkout is configured.</small>}</article></div>{balance?.subscription_status === "active" && <button className="text-button" disabled={busy} onClick={() => void manage()} type="button">Manage subscription in Stripe →</button>}</main></div>;
}
