import { useEffect, useMemo, useState } from "react";
import { createApi, type CreditBalance } from "./api";
import { BrandMark } from "./BrandMark";

export function BillingPage({ accessToken, onBack }: { accessToken?: string; onBack: () => void }) {
  const api = useMemo(() => createApi(accessToken), [accessToken]); const [balance, setBalance] = useState<CreditBalance>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const creditPrice = import.meta.env.VITE_CREDIT_PACK_PRICE_ID; const subscriptionPrice = import.meta.env.VITE_SUBSCRIPTION_PRICE_ID;
  useEffect(() => { void api.balance().then(setBalance).catch(() => setError("We could not load your credit balance.")); }, [api]);
  async function checkout(kind: "credits" | "subscription", priceId: string) { setBusy(true); setError(undefined); try { window.location.assign((await api.checkout(kind, priceId)).url); } catch { setError("We could not start checkout. Please try again."); setBusy(false); } }
  async function manage() { setBusy(true); try { window.location.assign((await api.portal()).url); } catch { setError("We could not open billing management."); setBusy(false); } }
  const credits = balance ? balance.subscription_remaining + balance.purchased_credits : 0;
  return <div className="workspace-shell"><header className="workspace-header"><button className="brand-button" onClick={onBack} type="button"><BrandMark /></button><button className="icon-button" onClick={onBack} type="button">Back to workspace</button></header><main className="billing-page"><p className="eyebrow">ACCOUNT & BILLING</p><h1>Keep your applications moving.</h1><p>Use your own Anthropic key anytime, or use Rezzie credits when you want the managed service.</p><section className="credit-summary"><strong>{credits}</strong><span>available Rezzie credits</span><small>{balance?.subscription_status === "active" ? "Your monthly plan is active." : "No active monthly plan."}</small></section>{error && <p className="auth-error" role="alert">{error}</p>}<div className="billing-plans"><article><p className="eyebrow">FLEX CREDITS</p><h2>Pay as you go</h2><p>Buy a small pack for the applications that matter most.</p>{creditPrice ? <button className="button button-primary" disabled={busy} onClick={() => void checkout("credits", creditPrice)} type="button">Buy {import.meta.env.VITE_CREDIT_PACK_CREDITS ?? "5"} credits</button> : <small>Credit packs will appear here when checkout is configured.</small>}</article><article className="featured"><p className="eyebrow">MONTHLY</p><h2>For an active search</h2><p>Receive a fresh monthly allowance and manage it whenever you need.</p>{subscriptionPrice ? <button className="button button-primary" disabled={busy} onClick={() => void checkout("subscription", subscriptionPrice)} type="button">Upgrade to monthly</button> : <small>Monthly plans will appear here when checkout is configured.</small>}</article></div>{balance?.subscription_status === "active" && <button className="text-button" disabled={busy} onClick={() => void manage()} type="button">Manage subscription in Stripe →</button>}</main></div>;
}
