export type BlogCategory = "Keyword strategy" | "Resume writing" | "Job search" | "Career clarity";

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: BlogCategory;
  publishedAt: string;
  readingMinutes: number;
  body: string[];
};

function articleBody(subject: string, firstStep: string, reviewQuestion: string): string[] {
  return [
    `${subject} works best when it starts with evidence, not a blank page. A job description is useful because it reveals the employer's language and priorities; your resume is useful because it shows what you can honestly support. The work is connecting those two documents without stretching either one.`,
    `${firstStep} Keep the source material close as you write. A strong revision is specific enough that you can explain it in an interview, yet plain enough that a recruiter can understand it in a fast first read.`,
    `Avoid treating every phrase in the posting as a demand to mirror. Repeated requirements matter more than one-off buzzwords, and context matters more than a long list of tools. If there is no truthful match, leave the claim out and decide how to address the gap elsewhere in your application.`,
    `Before you send the draft, ask: ${reviewQuestion} If the answer is unclear, simplify the sentence or return to the original source. A tailored resume should make your real experience easier to find—not make it harder to defend.`
  ];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "tailor-resume-to-job-description",
    title: "How to tailor a resume to a job description: a practical workflow",
    description: "A step-by-step process for matching your resume to a role's priorities without overstating your experience.",
    category: "Job search",
    publishedAt: "2026-09-08",
    readingMinutes: 8,
    body: [
      "Tailoring a resume is not the same thing as rebuilding your work history for every application. The useful goal is simpler: make it easy for a recruiter to see the connection between the work the employer needs done and the work you can honestly support. That means changing emphasis, wording, order, and examples—not adding achievements you cannot explain later.",
      "Start with the job description before opening your resume. Read it once for the overall purpose of the role, then a second time with a pen or notes app. Mark the responsibilities that appear early, are repeated, or are described with unusually specific language. Those are usually the themes a hiring team will use to decide whether a candidate looks relevant.",
      "Sort what you found into three groups: work the person will do, capabilities they need, and outcomes the employer cares about. For example, a product role may ask for customer research, prioritization, cross-functional delivery, and clearer adoption. A resume does not need to repeat every phrase, but it should make the strongest truthful evidence for the important groups visible.",
      "Next, build an evidence map. For each priority, find a project, responsibility, tool, or result in your existing resume that supports it. Use the actual details you have: the team you worked with, the decision you made, the system you improved, or the audience you served. If you cannot locate evidence, do not manufacture a match. A gap is information you can address in a cover letter, interview, or future learning plan—not a reason to create a claim.",
      "Use that map to revise the summary first. A strong summary identifies your real function, your most relevant domain or strengths, and the kind of value you have delivered. It should preview evidence that the experience section can substantiate. Avoid broad labels such as 'results-driven leader' unless the following bullets clearly show what that means in your work.",
      "Then revise the experience section. Put the most relevant bullets first within each job, replace vague verbs with accurate ones, and add context where it helps a reader understand why the work mattered. Instead of copying a requirement such as 'stakeholder management,' describe the real collaboration you did: coordinating research findings with product and engineering partners, for example. The job-description language becomes useful only when it remains attached to your experience.",
      "Finish with a fast quality check. Confirm that the target title, key skills, and important responsibilities are easy to find; that dates, employers, tools, and metrics still match your source resume; and that every highlighted phrase has a concrete story behind it. Save a separate version for the role so you can reuse the strongest structure for similar applications without losing your baseline resume.",
      "Rezzie can help turn this workflow into a reviewable draft: bring the resume you trust and the job description in front of you, then decide which edits accurately represent your experience before you apply.",
    ],
  },
  {
    slug: "ai-resume-tailoring-safety-checklist",
    title: "How to use AI to tailor a resume without lying",
    description: "Use AI to improve resume relevance while keeping employers, dates, skills, metrics, and achievements fully supportable.",
    category: "Resume writing",
    publishedAt: "2026-09-08",
    readingMinutes: 7,
    body: [
      "AI can make resume tailoring faster, but it cannot be the source of your career history. The safe use case is editorial: it can help identify relevant wording, tighten a bullet, reorganize supported details, and point out where the job description asks for evidence you may already have. It should not decide that you have used a tool, owned an outcome, held a title, or achieved a metric when you did not provide that information.",
      "Give the model dependable source material. Start with the full resume you trust, not a partial list of keywords. Add the relevant job description and, when helpful, a clearly labeled project note or portfolio source you personally confirm. More context helps the model make better connections, but it does not make unverified claims acceptable.",
      "Ask for bounded work. A useful request is 'prioritize the most relevant existing experience and use job-description terminology where it is accurate.' A risky request is 'make me the perfect candidate.' The first asks for clearer positioning; the second invites the system to close gaps that may not have a truthful answer.",
      "Review every newly emphasized claim for source support. Check employers, titles, dates, degrees, certifications, tools, scope, metrics, and outcomes. Quantitative claims deserve special attention because a small wording change can turn a real contribution into an unsupported result. If you cannot point to the source behind a sentence, remove it or rewrite it more precisely.",
      "Keep the difference between familiar and proficient clear. You may have collaborated with a team using a platform without operating it yourself, or participated in a launch without owning its commercial result. Good resume language can still explain adjacent experience, such as 'partnered with,' 'supported,' 'contributed to,' or 'worked alongside,' when those terms are true.",
      "Do not let keyword matching become keyword stuffing. Repeating the employer's phrase without an example makes a resume less credible to both a recruiter and the person who interviews you. Instead, connect a term to the setting where you used it. 'Conducted customer interviews to inform product priorities' is more useful than a skills list that only says 'customer research.'",
      "Use a final interview test: could you comfortably expand on every sentence in a conversation with the hiring manager? If not, the sentence needs more context, less certainty, or removal. This test protects the candidate as much as it protects the application; a resume should open the right conversation, not create one you have to explain away.",
      "Rezzie is designed around this review step. It can surface a focused draft and its changes, but you keep the decision about what stays. The strongest AI-assisted resume is not the one that sounds most impressive—it is the one that makes your real experience easiest to understand.",
    ],
  },
  { slug: "keyword-tailoring", title: "How to tailor resume keywords without keyword stuffing", description: "Match a resume to a job description while keeping every claim accurate and readable.", category: "Keyword strategy", publishedAt: "2026-09-05", readingMinutes: 5, body: articleBody("Keyword tailoring", "Group the posting into responsibilities, tools, and outcomes, then find the evidence already present in your resume.", "could you point to a project, responsibility, or result behind every emphasized phrase?") },
  { slug: "honest-resume-tailoring", title: "What honest AI resume tailoring should and should not change", description: "The line between clearer positioning and invented experience in an AI-tailored resume.", category: "Resume writing", publishedAt: "2026-09-04", readingMinutes: 6, body: articleBody("Honest AI resume tailoring", "Change emphasis, order, headings, and phrasing before you ever consider adding new language.", "would this statement still be true if a hiring manager asked for an example?") },
  { slug: "job-description", title: "A simple way to read a job description before rewriting your resume", description: "Break a job description into priorities before you start editing.", category: "Job search", publishedAt: "2026-09-03", readingMinutes: 4, body: articleBody("Reading a job description", "Separate must-have requirements from preferred qualifications and recurring themes.", "have you made the role's most important supported requirement easy to notice?") },
  { slug: "resume-summary", title: "How to write a resume summary that does not overpromise", description: "Use a summary to frame supported strengths without making broad claims you cannot prove.", category: "Resume writing", publishedAt: "2026-09-02", readingMinutes: 5, body: articleBody("A resume summary", "Start with your function, strongest relevant domain, and the kind of work you have actually delivered.", "does each line introduce evidence that appears later in the resume?") },
  { slug: "achievement-bullets", title: "Turn responsibilities into stronger resume bullets", description: "A practical way to clarify contribution, context, and outcomes without inventing metrics.", category: "Resume writing", publishedAt: "2026-09-01", readingMinutes: 6, body: articleBody("Stronger resume bullets", "Choose one responsibility and add the decision, collaboration, or result you can genuinely describe.", "does the bullet show what you did rather than merely naming a team activity?") },
  { slug: "transferable-skills", title: "How to show transferable skills when changing careers", description: "Translate real experience into the language of a new role without pretending you already held it.", category: "Career clarity", publishedAt: "2026-08-31", readingMinutes: 6, body: articleBody("Transferable skills", "Map the new role's core responsibilities to adjacent work you have actually performed.", "have you explained the bridge without claiming direct experience you do not have?") },
  { slug: "ats-basics", title: "What applicant tracking systems actually need from your resume", description: "Focus on clean structure and meaningful terminology instead of formatting tricks.", category: "Keyword strategy", publishedAt: "2026-08-30", readingMinutes: 5, body: articleBody("ATS-friendly writing", "Use conventional headings, readable text, and terminology that appears naturally in your experience.", "would a person still find this resume clear if no scanner existed?") },
  { slug: "skills-section", title: "Build a skills section that helps instead of distracts", description: "Choose skills that are supported by experience and relevant to the target role.", category: "Resume writing", publishedAt: "2026-08-29", readingMinutes: 4, body: articleBody("A skills section", "Prioritize the skills you can demonstrate in your work history, projects, or training.", "can you show where each important skill was used?") },
  { slug: "experience-order", title: "When to reorder experience for a specific role", description: "Use order and emphasis to surface relevant work while preserving an accurate timeline.", category: "Resume writing", publishedAt: "2026-08-28", readingMinutes: 5, body: articleBody("Reordering experience", "Keep your chronology honest, then move the most role-relevant bullets and projects higher within each section.", "does the new order help a reader understand the fit without hiding important context?") },
  { slug: "resume-length", title: "How long should a resume be? Start with relevance", description: "Make space decisions based on evidence and role fit, not arbitrary page-count rules.", category: "Career clarity", publishedAt: "2026-08-27", readingMinutes: 4, body: articleBody("Resume length", "Cut repetition and low-relevance detail before cutting the evidence that explains your strongest fit.", "does every section earn its space for this particular application?") },
  { slug: "project-section", title: "Use projects to strengthen a resume without padding it", description: "Add projects when they provide relevant, defensible evidence missing from work history.", category: "Resume writing", publishedAt: "2026-08-26", readingMinutes: 5, body: articleBody("A project section", "Select projects that show a requirement the role values and describe your own contribution precisely.", "does the project add a new proof point rather than repeat the experience section?") },
  { slug: "job-search-notes", title: "Keep a job-search evidence bank for faster tailoring", description: "A simple private record of projects, outcomes, and examples makes future tailoring safer.", category: "Job search", publishedAt: "2026-08-25", readingMinutes: 5, body: articleBody("An evidence bank", "Save concise notes about projects while the details are fresh, including your role and source context.", "could you find the original detail if you needed to verify it later?") },
  { slug: "gap-explanation", title: "Address career gaps with clarity, not apology", description: "Use direct, accurate context and keep the focus on the experience you bring now.", category: "Career clarity", publishedAt: "2026-08-24", readingMinutes: 4, body: articleBody("A career gap", "Decide what brief context is useful, then return the reader's attention to relevant work and capabilities.", "is the explanation truthful, proportionate, and appropriate for a resume?") },
  { slug: "cover-letter-resume", title: "Make your resume and cover letter do different jobs", description: "Avoid duplicating documents by giving each one a clear role in your application.", category: "Job search", publishedAt: "2026-08-23", readingMinutes: 5, body: articleBody("Resume and cover-letter alignment", "Let the resume prove your experience while the letter explains motivation, context, and the connection to the role.", "would a reader learn something useful from each document?") },
  { slug: "leadership-language", title: "Use leadership language only when you can support it", description: "Describe influence, ownership, and collaboration precisely instead of relying on inflated labels.", category: "Resume writing", publishedAt: "2026-08-22", readingMinutes: 5, body: articleBody("Leadership language", "Name the decision, coordination, mentorship, or accountability you actually held.", "does the wording describe your contribution without implying authority you did not have?") },
  { slug: "technical-keywords", title: "How to use technical keywords with context", description: "Show where and why you used a tool so a skills list becomes credible evidence.", category: "Keyword strategy", publishedAt: "2026-08-21", readingMinutes: 5, body: articleBody("Technical keywords", "Pair important tools with the project or responsibility where you used them.", "does the reader understand your level of practical experience with the tool?") },
  { slug: "entry-level-resume", title: "Build an entry-level resume around evidence you already have", description: "Use coursework, projects, volunteering, and part-time work honestly and strategically.", category: "Career clarity", publishedAt: "2026-08-20", readingMinutes: 6, body: articleBody("An entry-level resume", "Collect examples of responsibility, learning, collaboration, and outcomes from every credible setting.", "have you described what you did without turning a learning experience into a job title?") },
  { slug: "recruiter-scan", title: "The 30-second recruiter scan: what to make visible", description: "Help a reader understand role fit quickly with clear headings and supported priorities.", category: "Job search", publishedAt: "2026-08-19", readingMinutes: 4, body: articleBody("The recruiter scan", "Place your relevant title, summary, skills, and strongest recent evidence where they are easy to find.", "could someone identify your fit before reading every bullet?") },
  { slug: "tailoring-checklist", title: "A final resume-tailoring checklist before you apply", description: "Use a short review to catch unsupported claims, missing context, and avoidable errors.", category: "Job search", publishedAt: "2026-08-18", readingMinutes: 4, body: articleBody("A final tailoring review", "Compare the draft with both the source resume and the job description one last time.", "is every adjustment relevant, readable, and supportable?") },
  { slug: "resume-voice", title: "Keep your voice while tailoring your resume", description: "A tailored document can use the employer's language without becoming generic or artificial.", category: "Resume writing", publishedAt: "2026-08-17", readingMinutes: 5, body: articleBody("Resume voice", "Keep the verbs and examples that accurately reflect how you work, then sharpen the connection to the role.", "does the draft sound like a clearer version of you rather than a template?") },
  { slug: "job-title-matching", title: "Match job titles carefully when your title was different", description: "Clarify an equivalent function without rewriting your employment history.", category: "Keyword strategy", publishedAt: "2026-08-16", readingMinutes: 4, body: articleBody("Job title matching", "Keep your official title and use a short clarifier only where it accurately explains the function.", "would your former employer recognize the title and context as accurate?") },
  { slug: "application-strategy", title: "Choose which jobs deserve a tailored resume first", description: "Focus your time on roles where you have enough relevant, supported evidence to make a strong case.", category: "Job search", publishedAt: "2026-08-15", readingMinutes: 5, body: articleBody("Application prioritization", "Compare the role's core requirements with your strongest evidence before investing in a detailed rewrite.", "can you make a convincing, honest case for the priorities that matter most?") },
  { slug: "resume-review", title: "How to review a tailored resume before sending it", description: "A calm, evidence-first review process for the final version of your application.", category: "Resume writing", publishedAt: "2026-08-14", readingMinutes: 5, body: articleBody("Resume review", "Read the document aloud, check each emphasized claim against your sources, and confirm the contact details.", "would you be comfortable expanding on every line in a live conversation?") }
];

export const blogCategories: Array<BlogCategory | "All"> = ["All", "Keyword strategy", "Resume writing", "Job search", "Career clarity"];
