import heroImage from "./assets/rezzie-hero-editorial.png";
import { BrandMark } from "./BrandMark";

export function LandingPage({ onStart }: { onStart: () => void }) {
  return <main className="landing"><nav className="site-nav"><BrandMark/><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#trust">Our promise</a><button className="nav-cta" onClick={onStart} type="button">Tailor a resume <span>↗</span></button></div></nav>
    <section className="hero"><div className="hero-copy"><p className="kicker"><i/> RESUME TAILORING, WITH RECEIPTS</p><h1>Stand out for<br/>the <em>right</em> reasons.</h1><p className="hero-lede">Rezzie reshapes your existing experience around each role—so every line is more relevant, never more fictional.</p><div className="hero-actions"><button className="cta" onClick={onStart} type="button">Tailor my resume <span>→</span></button><a href="#how-it-works">See how it works <span>↓</span></a></div><p className="microcopy">Bring your own Anthropic key, or use Rezzie credits.</p></div><div className="hero-art"><img src={heroImage} alt="Editorial arrangement of resume papers, a green folder, pencil, and paperclip"/><div className="proof-card"><span className="proof-number">01</span><p>Every change begins with<br/><strong>your actual experience.</strong></p><span className="proof-line"/></div></div></section>
    <section className="marquee" aria-label="Rezzie benefits"><span>Grounded in your resume</span><b>✦</b><span>Built for the role in front of you</span><b>✦</b><span>Always yours to review</span><b>✦</b></section>
    <section className="intro-section" id="how-it-works"><p className="section-label">THE REZZIE METHOD / 01—03</p><div className="section-heading"><h2>A sharper story,<br/>without a taller tale.</h2><p>Job descriptions are noisy. Your experience is not. Rezzie finds the overlap, reorganizes the signal, and leaves the final call with you.</p></div><div className="method-grid"><article><span>01</span><h3>Bring the brief.</h3><p>Paste a JD, import a job link, or upload the posting you care about.</p><div className="diagram source-diagram"><i/><i/><i/><i/></div></article><article><span>02</span><h3>Find the fit.</h3><p>Rezzie maps relevant language back to the experience already in your resume.</p><div className="diagram fit-diagram"><i>YOU</i><b>↔</b><i>ROLE</i></div></article><article><span>03</span><h3>Review every word.</h3><p>Get a tailored draft, keyword context, and anything that needs your judgment.</p><div className="diagram review-diagram"><i>✓</i><i>✓</i><i>?</i></div></article></div></section>
    <section className="promise-section" id="trust"><div><p className="section-label light">A BETTER KIND OF AI ASSISTANCE</p><h2>Your career is<br/>not a prompt.</h2></div><div className="promise-copy"><p>It is a record of work you actually did. Rezzie is designed to protect that line: no invented credentials, no made-up metrics, no confident fiction.</p><ul><li><b>↗</b> Your resume is the source of truth.</li><li><b>↗</b> Unsupported requirements stay in review.</li><li><b>↗</b> You approve the final version.</li></ul><button className="cta coral" onClick={onStart} type="button">Start with your resume <span>→</span></button></div></section>
    <section className="closing-section"><p className="section-label">MAKE THE APPLICATION COUNT</p><h2>Ready to make<br/><em>your case?</em></h2><button className="cta" onClick={onStart} type="button">Open Rezzie <span>→</span></button></section>
    <footer><BrandMark/><p>Tailor the signal. Keep the truth.</p><span>© {new Date().getFullYear()} Rezzie</span></footer>
  </main>;
}
