import { useEffect, useMemo, useState } from "react";
import { blogCategories, blogPosts, type BlogCategory, type BlogPost } from "./blog";
import { PublicFooter, PublicHeader } from "./SiteChrome";

type PageKind = "about" | "features" | "how-it-works" | "safety" | "pricing" | "faq" | "blog" | "blog-post";

function Seo({ post, title, description }: { post?: BlogPost; title: string; description: string }) { useEffect(() => { const url = `https://rezzie.org${window.location.pathname}`; document.title = `${title} | Rezzie`; const set = (key: string, value: string) => { let node = document.head.querySelector(`meta[property="${key}"],meta[name="${key}"]`) as HTMLMetaElement | null; if (!node) { node = document.createElement("meta"); node.setAttribute(key.includes(":") ? "property" : "name", key); document.head.append(node); } node.content = value; }; set("description", description); set("og:title", title); set("og:description", description); set("og:url", url); set("og:image", "https://rezzie.org/social-preview.svg"); set("twitter:card", "summary_large_image"); let canonical = document.head.querySelector('link[rel="canonical"]') as HTMLLinkElement | null; if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.append(canonical); } canonical.href = url; let script = document.head.querySelector("script[data-rezzie-schema]"); if (!script) { script = document.createElement("script"); script.setAttribute("data-rezzie-schema", ""); script.setAttribute("type", "application/ld+json"); document.head.append(script); } script.textContent = JSON.stringify(post ? { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, datePublished: post.publishedAt, author: { "@type": "Organization", name: "Rezzie" }, mainEntityOfPage: url } : { "@context": "https://schema.org", "@type": "WebPage", name: title, description, url }); }, [description, post, title]); return null; }
function Meta({ post }: { post: BlogPost }) { return <p className="post-meta"><span>{post.category}</span><span>Rezzie Editorial</span><time dateTime={post.publishedAt}>{new Date(`${post.publishedAt}T12:00:00Z`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</time><span>{post.readingMinutes} min read</span></p>; }
function Blog({ onStart }: { onStart: () => void }) { const [category, setCategory] = useState<BlogCategory | "All">("All"); const [query, setQuery] = useState(""); const posts = useMemo(() => blogPosts.filter(post => (category === "All" || post.category === category) && `${post.title} ${post.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]); return <main className="content-page blog-index"><Seo title="Resume tailoring guides" description="Practical guides for job descriptions, resumes, keywords, and job search strategy." /><p className="eyebrow">REZZIE FIELD NOTES</p><h1>Make the next application easier to explain.</h1><p className="page-lede">Practical guides for tailoring a truthful resume, interpreting job descriptions, and keeping your job search organized.</p><div className="blog-controls"><input aria-label="Search guides" onChange={event => setQuery(event.target.value)} placeholder="Search guides" type="search" value={query} /><div className="category-list">{blogCategories.map(item => <button className={item === category ? "active" : ""} key={item} onClick={() => setCategory(item)} type="button">{item}</button>)}</div></div><p className="results-count">{posts.length} guides</p><div className="article-grid">{posts.map(post => <a className="article-card" href={`/blog/${post.slug}`} key={post.slug}><Meta post={post} /><h2>{post.title}</h2><p>{post.description}</p><span>Read guide →</span></a>)}</div><button className="button button-primary page-cta" onClick={onStart} type="button">Start tailoring →</button></main>; }
const pages = { about: ["About Rezzie", "A better match should still be your story."], features: ["Resume tailoring features", "Tools for a sharper, truthful application."], "how-it-works": ["How Rezzie works", "A focused flow, from source to draft."], safety: ["Truth-preserving resume tailoring", "Your career is not a prompt."], pricing: ["Rezzie pricing", "Choose the access that fits your search."], faq: ["Resume tailoring FAQ", "Questions, answered plainly."] } as const;
export function MarketingPage({ isAuthenticated, kind, onSignIn, onStart }: { isAuthenticated: boolean; kind: PageKind; onSignIn?: () => void; onStart: () => void }) { const slug = window.location.pathname.split("/").filter(Boolean).at(-1); const post = kind === "blog-post" ? blogPosts.find(item => item.slug === slug) : undefined; return <div className="landing"><PublicHeader isAuthenticated={isAuthenticated} onSignIn={onSignIn} onStart={onStart} />{kind === "blog" ? <Blog onStart={onStart} /> : post ? <main className="content-page article-page"><Seo description={post.description} post={post} title={post.title} /><p className="eyebrow">REZZIE FIELD NOTES</p><Meta post={post} /><h1>{post.title}</h1><p className="page-lede">{post.description}</p>{post.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</main> : <Static kind={kind as keyof typeof pages} onStart={onStart} />}<PublicFooter /></div>; }
function Static({ kind, onStart }: { kind: keyof typeof pages; onStart: () => void }) { const [title, heading] = pages[kind]; return <main className="content-page"><Seo description={heading} title={title} /><p className="eyebrow">REZZIE</p><h1>{heading}</h1><p className="page-lede">Clearer positioning, supported claims, and a final draft you control.</p><div className="content-grid">{["Bring the right sources", "Keep every claim supported", "Review before you send"].map(item => <article key={item}><h2>{item}</h2><p>Make relevant evidence easy to find while retaining your own judgment and accuracy.</p></article>)}</div><button className="button button-primary page-cta" onClick={onStart} type="button">Start tailoring →</button></main>; }
